cabal-version:       2.4
name:                mac-iwsbp
version:             0.1
license:             BSD-2-Clause
author:              John Smith <john@example.com>
maintainer:          John Smith <john@example.com>

common common-options
  default-extensions:
    AllowAmbiguousTypes
    BangPatterns
    BinaryLiterals
    ConstraintKinds
    DataKinds
    DefaultSignatures
    DeriveAnyClass
    DeriveDataTypeable
    DeriveFoldable
    DeriveFunctor
    DeriveGeneric
    DeriveLift
    DeriveTraversable
    DerivingStrategies
    DerivingVia
    DuplicateRecordFields
    FlexibleContexts
    InstanceSigs
    KindSignatures
    LambdaCase
    NamedFieldPuns
    NoStarIsType
    PolyKinds
    RankNTypes
    RecordWildCards
    ScopedTypeVariables
    StandaloneDeriving
    TupleSections
    TypeApplications
    TypeFamilies
    TypeOperators
    ViewPatterns

    -- TemplateHaskell is used to support convenience functions such as
    -- 'listToVecTH' and 'bLit'.
    TemplateHaskell
    QuasiQuotes

    -- Prelude isn't imported by default as Clash offers Clash.Prelude
    NoImplicitPrelude
  ghc-options:
    -Wall -Wcompat
    -haddock

    -- Plugins to support type-level constraint solving on naturals
    -fplugin GHC.TypeLits.Extra.Solver
    -fplugin GHC.TypeLits.Normalise
    -fplugin GHC.TypeLits.KnownNat.Solver

    -- Clash needs access to the source code in compiled modules
    -fexpose-all-unfoldings

    -- Worker wrappers introduce unstable names for functions that might have
    -- blackboxes attached for them. You can disable this, but be sure to add
    -- a no-specialize pragma to every function with a blackbox.
    -fno-worker-wrapper

    -- Strict annotations - while sometimes preventing space leaks - trigger
    -- optimizations Clash can't deal with. See:
    --
    --    https://github.com/clash-lang/clash-compiler/issues/2361
    --
    -- These flags disables these optimizations. Note that the fields will
    -- remain strict.
    -fno-unbox-small-strict-fields
    -fno-unbox-strict-fields
  build-depends:
    base,
    Cabal,
    extra,
    -- clash-prelude will set suitable version bounds for the plugins
    clash-prelude >= 1.10.0 && < 1.12,
    ghc-typelits-natnormalise,
    ghc-typelits-extra,
    ghc-typelits-knownnat,

    mtl,
    string-interpolate,
    text


library
  import: common-options
  hs-source-dirs: src
  exposed-modules:
    Benchmarks.Full
    Benchmarks.Paper
    Benchmarks.Test
    MAC.BVec
    MAC.Class.Storage
    MAC.Config
    MAC.Constraints
    MAC.Extended
    MAC.Extended.Access.Indexing
    MAC.Extended.Access.Rotating
    MAC.Extended.Mealy
    MAC.Extended.Monad
    MAC.Extended.Stage
    MAC.Extended.State
    MAC.IO
    MAC.OneHotCounter
    MAC.Simple
    MAC.Simple.Access.Indexing
    MAC.Simple.Access.Rotating
    MAC.Simple.Mealy
    MAC.Simple.Monad
    MAC.Simple.Stage
    MAC.Simple.State
    Util
    Util.FullAdder
    Util.IWSBP
  default-language: Haskell2010

-- Builds the executable 'clash', with mac-iwsbp project in scope
executable clash
  main-is: bin/Clash.hs
  default-language: Haskell2010
  Build-Depends: base, clash-ghc, mac-iwsbp
  -- Use the RTS options that upstream clash uses for better performance:
  -- https://github.com/clash-lang/clash-compiler/blob/daef4893dee4910ab4eced0c141a39d40d88996a/changelog/2026-05-06T15_20_00%2B02_00_ghc_style_rts_defaults
  ghc-options: "-with-rtsopts=-K512M -H -I5 -T"
  if !os(Windows)
    ghc-options: -dynamic

-- Builds the executable 'clashi', with mac-iwsbp project in scope
executable clashi
  main-is: bin/Clashi.hs
  default-language: Haskell2010
  ghc-options: "-with-rtsopts=-K512M -H -I5 -T"
  if !os(Windows)
    ghc-options: -dynamic
  build-depends: base, clash-ghc, mac-iwsbp

test-suite doctests
  type:             exitcode-stdio-1.0
  default-language: Haskell2010
  main-is:          doctests.hs
  ghc-options:      -Wall -Wcompat -threaded
  hs-source-dirs:   tests
  build-depends:
    base,
    mac-iwsbp,
    doctest-parallel >= 0.2 && < 0.5,

test-suite test-library
  import: common-options
  default-language: Haskell2010
  hs-source-dirs: tests
  type: exitcode-stdio-1.0
  ghc-options: -threaded
  main-is: unittests.hs
  other-modules:
    Tests.MAC
    Tests.MAC.Extended
    Tests.MAC.Extended.Exhaustive
    Tests.MAC.Extended.Exhaustive.Internal
    Tests.MAC.Extended.Exhaustive.TestTrees
    Tests.MAC.Extended.Random
    Tests.MAC.Extended.Random.Internal
    Tests.MAC.Extended.Random.TestTrees
    Tests.MAC.Simple
    Tests.MAC.Simple.Exhaustive
    Tests.MAC.Simple.Exhaustive.TestTrees
    Tests.MAC.Simple.Exhaustive.Internal
    Tests.MAC.Simple.Random
    Tests.MAC.Simple.Random.TestTrees
    Tests.MAC.Simple.Random.Internal
    Tests.OneHot
    Tests.Util
  build-depends:
    mac-iwsbp,
    QuickCheck,
    clash-prelude-hedgehog,
    hedgehog,
    tasty >= 1.2 && < 1.6,
    tasty-hedgehog,
    tasty-hunit,
    tasty-th,
    arrows,
    IfElse
