module Tests.OneHot where

import Test.Tasty
import Test.Tasty.HUnit

import Clash.Prelude
import Clash.Class.Counter

import Control.Monad

import MAC.OneHotCounter
import Util

tests :: TestTree
tests = testGroup "OneHot Counter" [
    trippingTests,
    countingTests
  ]

countingTests :: TestTree
countingTests = testGroup "Counting Tests" [
  countingTest @2,
  countingTest @3,
  countingTest @4,
  countingTest @5,
  countingTest @6,
  countingTest @7,
  countingTest @8,
  countingTest @9,
  countingTest @10,
  countingTest @11,
  countingTest @12,
  countingTest @13,
  countingTest @14,
  countingTest @15,
  countingTest @16,
  countingTest @17,
  countingTest @18,
  countingTest @19,
  countingTest @20,
  countingTest @21,
  countingTest @22,
  countingTest @23,
  countingTest @24,
  countingTest @25,
  countingTest @26,
  countingTest @27,
  countingTest @28,
  countingTest @29,
  countingTest @30,
  countingTest @31,
  countingTest @32,
  countingTest @33,
  countingTest @34,
  countingTest @35,
  countingTest @36,
  countingTest @37,
  countingTest @38,
  countingTest @39,
  countingTest @40,
  countingTest @41,
  countingTest @42,
  countingTest @43,
  countingTest @44,
  countingTest @45,
  countingTest @46,
  countingTest @47,
  countingTest @48,
  countingTest @49,
  countingTest @50,
  countingTest @51,
  countingTest @52,
  countingTest @53,
  countingTest @54,
  countingTest @55,
  countingTest @56,
  countingTest @57,
  countingTest @58,
  countingTest @59,
  countingTest @60,
  countingTest @61,
  countingTest @62,
  countingTest @63,
  countingTest @64,
  countingTest @65,
  countingTest @66,
  countingTest @67,
  countingTest @68,
  countingTest @69,
  countingTest @70,
  countingTest @71,
  countingTest @72,
  countingTest @73,
  countingTest @74,
  countingTest @75,
  countingTest @76,
  countingTest @77,
  countingTest @78,
  countingTest @79,
  countingTest @80,
  countingTest @81,
  countingTest @82,
  countingTest @83,
  countingTest @84,
  countingTest @85,
  countingTest @86,
  countingTest @87,
  countingTest @88,
  countingTest @89,
  countingTest @90,
  countingTest @91,
  countingTest @92,
  countingTest @93,
  countingTest @94,
  countingTest @95,
  countingTest @96,
  countingTest @97,
  countingTest @98,
  countingTest @99,
  countingTest @100,
  countingTest @101,
  countingTest @102,
  countingTest @103,
  countingTest @104,
  countingTest @105,
  countingTest @106,
  countingTest @107,
  countingTest @108,
  countingTest @109,
  countingTest @110,
  countingTest @111,
  countingTest @112,
  countingTest @113,
  countingTest @114,
  countingTest @115,
  countingTest @116,
  countingTest @117,
  countingTest @118,
  countingTest @119,
  countingTest @120,
  countingTest @121,
  countingTest @122,
  countingTest @123,
  countingTest @124,
  countingTest @125,
  countingTest @126,
  countingTest @127,
  countingTest @128
  ]

countingTest :: forall n. (KnownNat n) => TestTree
countingTest = testCase name (go 0 (countMin :: (OneHotCounter n)))
  where
    name = "Couting n=" <> prettySNat @n
    go n cnt = let (ovfl, cnt') = countSuccOverflow cnt in do
        if ovfl
          then n @?= (natToNum @n @Int) - 1
          else go (n+1) cnt'


trippingTest :: forall n. (KnownNat n) => TestTree
trippingTest = testCase name (go (countMin :: (OneHotCounter n)))
  where
    name = "Tripping n=" <> prettySNat @n
    go cnt = let (ovfl, cnt') = countSuccOverflow cnt in do
        (toEnum . fromEnum) cnt @?= cnt
        when (not ovfl) $ go cnt'


trippingTests :: TestTree
trippingTests = testGroup "Tripping Tests" [
  trippingTest @2,
  trippingTest @3,
  trippingTest @4,
  trippingTest @5,
  trippingTest @6,
  trippingTest @7,
  trippingTest @8,
  trippingTest @9,
  trippingTest @10,
  trippingTest @11,
  trippingTest @12,
  trippingTest @13,
  trippingTest @14,
  trippingTest @15,
  trippingTest @16,
  trippingTest @17,
  trippingTest @18,
  trippingTest @19,
  trippingTest @20,
  trippingTest @21,
  trippingTest @22,
  trippingTest @23,
  trippingTest @24,
  trippingTest @25,
  trippingTest @26,
  trippingTest @27,
  trippingTest @28,
  trippingTest @29,
  trippingTest @30,
  trippingTest @31,
  trippingTest @32,
  trippingTest @33,
  trippingTest @34,
  trippingTest @35,
  trippingTest @36,
  trippingTest @37,
  trippingTest @38,
  trippingTest @39,
  trippingTest @40,
  trippingTest @41,
  trippingTest @42,
  trippingTest @43,
  trippingTest @44,
  trippingTest @45,
  trippingTest @46,
  trippingTest @47,
  trippingTest @48,
  trippingTest @49,
  trippingTest @50,
  trippingTest @51,
  trippingTest @52,
  trippingTest @53,
  trippingTest @54,
  trippingTest @55,
  trippingTest @56,
  trippingTest @57,
  trippingTest @58,
  trippingTest @59,
  trippingTest @60,
  trippingTest @61,
  trippingTest @62,
  trippingTest @63,
  trippingTest @64,
  trippingTest @65,
  trippingTest @66,
  trippingTest @67,
  trippingTest @68,
  trippingTest @69,
  trippingTest @70,
  trippingTest @71,
  trippingTest @72,
  trippingTest @73,
  trippingTest @74,
  trippingTest @75,
  trippingTest @76,
  trippingTest @77,
  trippingTest @78,
  trippingTest @79,
  trippingTest @80,
  trippingTest @81,
  trippingTest @82,
  trippingTest @83,
  trippingTest @84,
  trippingTest @85,
  trippingTest @86,
  trippingTest @87,
  trippingTest @88,
  trippingTest @89,
  trippingTest @90,
  trippingTest @91,
  trippingTest @92,
  trippingTest @93,
  trippingTest @94,
  trippingTest @95,
  trippingTest @96,
  trippingTest @97,
  trippingTest @98,
  trippingTest @99,
  trippingTest @100,
  trippingTest @101,
  trippingTest @102,
  trippingTest @103,
  trippingTest @104,
  trippingTest @105,
  trippingTest @106,
  trippingTest @107,
  trippingTest @108,
  trippingTest @109,
  trippingTest @110,
  trippingTest @111,
  trippingTest @112,
  trippingTest @113,
  trippingTest @114,
  trippingTest @115,
  trippingTest @116,
  trippingTest @117,
  trippingTest @118,
  trippingTest @119,
  trippingTest @120,
  trippingTest @121,
  trippingTest @122,
  trippingTest @123,
  trippingTest @124,
  trippingTest @125,
  trippingTest @126,
  trippingTest @127,
  trippingTest @128
  ]
